vertices = ['A Tribuna, terapeutas\ne psicanalistas', 'A Tribuna', 'Dilma Ribeiro', 'Cássia Rodrigues', 'Farmácia João Manoel', 'Paloma', 'João Manoel', 'Acabei', 'Priscilla Plastino', 'Lauro Arthur', 'Vitória', 
'Mariana', 'Relacionamento', 'Dilma', 'Vale', 'Dou', 'Lauro', 'Cássia', 'ERROS \nPapel de homem\nPor', 'Priscilla', 'Cobrar', 'Mãe', 'George Bush', 'Estados Unidos', 'amanhã', 'Ficarão', 'Relações Exteriores', 'Celso', 'Julier Sebastião da Silva', 'Polícia', 'ordem de Silva', 'Associação dos Juízes', 'Bush', 'Fidel Castro', 'Assad', 'Kadafi', 'Lula', 'Mato Grosso do Sul', 'São Paulo', 'Sociedade Mineira de Cardiologia', 'Coisa', 'Brasil', 'Pindorama', 'Tratamento George W. Bush', 'casa da sogra.   ', 'Festival de Alegre', 'A Tribuna.\n', 'Silvio Santos', 'Valia', 'Concurso Público', 'Estudos Preliminares', 'Anteprojetos de Arquitetura', 'Petrobras', 'Instituto de Arquitetos do Brasil', 'R$', 'Serginho', 'Marcão', 'Jean', 'Fla-Flu', 'Maria', 'Portugal', 'Dona Maria I', 'D', 'João VI', 'D. Pedro I', 'D. Pedro II', 'D. Maria', 'O Pulo do Gato”', 'Márcio Cotrim', 'O Dia Mundial sem Tabaco', 'Sociedade Paulista de Oncologia Clínica', 'I Caminhada', 'Convenção-Quadro', 'Controle do Tabaco.\n', 'Senado Federal', 'Emar Batalha', 'Luciene Pretti', 'Neuza Balarine', 'Michel Magno Vasconcelos', 'Universidade Federal Fluminense', 'Roberto DaMatta', 'Michael', 'banca', 'Movelar', 'Associação Brasileira das Indústrias do Mobiliário', 'Domingos Rigoni', 'IFórum', 'Centro de Convenções de Vitória', 'Ivan', 'Associação Brasileira de Celulose', 'Luiz Antônio', 'Casaca', 'Associação dos Surdos', 'Feira da Paz', 'Renato Casanova', 'Garças do Jucu”', 'Festa', 'São Pedro', 'Procissão', 'Praia do Suá', 'jet skis', 'baía de Vitória', 'Centro', 'Convento da Penha', 'Cruz do Papa', 'Benção do Anzol', 'José Pedro Rodrigues',
 'João Coser', 'Procissão Marítima', 'PREMIAÇÃO \nAntes', 'Copa do Mundo', 'Bussunda', 'Rede Tribuna', 'PLANETA', 'McCartney', 'Lennon\n \nPaul McCartney', 'John Lennon', 'Nova Iorque', 'John', 'Beatle', '“Chaos and Creation in the Backyard”.\n', 'Miami', 'Beatles', 'Gisele Bündchen', 'Hollywood', 'Mulher Maravilha”', 'Warner Bros', 'Joss Whedon', 'Gisele', 'Sandra Bullock', 'Catherina', 'Leonardo DiCaprio', 'Volta da França', 'Lance', 'Sheryl Crow', 'Mãe sexy\n', 'Kate', 'Inglaterra', 'Sam Mendes', 'Joe', 'Elle', 'ex-Spice Girl Victoria', 'Gwyneth Paltrow', 'Elizabeth Hurley', 'Festival de Veneza', 'Abel Ferrara', 'Romance & Cigarettes', 'John Turturro', 'Festival de Veneza.\n\n\n', 'Guy Ritchie', 'Madonna', 'Rocco', 'Lourdes', 'Carlos Leon', 'Gosto', 'Jerry Hall', 'Mick Jagger', 'LWren', 'Jagger', 'Fui', 'Hall', 'Carmen Electra', 'Aeros LLC', 'MTV americana', 'Cate Blanchett', 'Oscar']

for x in vertices:
    x = {"nome": x}
    print(x)


print(x)